### ISSUE TITLE
chgres metadata in output

### ISSUE THREAD

**Issue by jedwards4b** [NOAA-EMC/UFS_UTILS#114]
chgres should include metadata in it's output to identify the source of it's input, this data should be enough to reproduce the contents of the file.

**Comment by GeorgeGayno-NOAA** [comment]
Is this request already part of #97?  Or is this something new?

Maybe @JeffBeck-NOAA can comment.

**Comment by jedwards4b** [comment]
Please see https://github.com/ufs-community/ufs-mrweather-app/issues/65 for more details.

**Comment by JeffBeck-NOAA** [comment]
@GeorgeGayno-NOAA I think this issue could definitely be related to the documentation request from #97.  There is already a SOURCE chgres_cube output metadata flag which defines the source external model, but it is hardwired in ufs-weather-model at the moment to perform specific modifications of input data.  Therefore, at the moment, it has to be defined as "FV3GFS GAUSSIAN NEMSIO FILE" regardless of source data.  Please see my issue for this problem here: https://github.com/ufs-community/ufs-weather-model/issues/97

**Comment by GeorgeGayno-NOAA** [comment]
@jedwards4b and @JeffBeck-NOAA This issue has not been updated in a year. Can we close it? Has it been superceded by #539?

**Comment by jedwards4b** [comment]
@GeorgeGayno-NOAA I'm no longer on the project.

**Comment by JeffBeck-NOAA** [comment]
@GeorgeGayno-NOAA, I think #539 will cover this issue.

**Comment by GeorgeGayno-NOAA** [comment]
Superceded by #539. Closing.
