### ISSUE TITLE
Reorder enkf outputs from gdas_init to align with new global workflow structure

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UFS_UTILS#762]
The global workflow gdasenkf directory structure was changed in PR noaa-emc/global-workflow#1201 from `enkfgdas.YYYYMMDD/CC/atmos/memXXX` to `enkfgdas.YYYYMMDD/CC/memXXX/atmos`.  The output structure of gdas_init should be modified to match.

**Comment by GeorgeGayno-NOAA** [comment]
@DavidHuber-NOAA This appears to be an easy fix. I can try to work on it today.

**Comment by GeorgeGayno-NOAA** [comment]
@DavidHuber-NOAA Can you try my branch at 5d5bc76.

**Comment by DavidHuber-NOAA** [comment]
@GeorgeGayno-NOAA This works and all outputs are bitwise identical when compared to the current develop branch.  Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA This works and all outputs are bitwise identical when compared to the current develop branch. Thanks!

I will open a PR.

**Comment by GeorgeGayno-NOAA** [comment]
As a future improvement, we should try to combine the various chgres run scripts into one so that a change such as this can be made in one place. There may also be a way to combine the driver scipts for each machine. The data pull scripts are very different because the GFS/GDAS tarballs have changed so much over the years. So I don't think the data scripts can be combined.
