### ISSUE TITLE
Merge regional chgres updates into authoritative repository

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/UFS_UTILS#92]
Current using two UFS_UTILS branches for all functionality (dtc/develop and feature/chgres_grib2 in https://github.com/NCAR/UFS_UTILS)

**Comment by jwolff-ncar** [comment]
@LarissaReames-NOAA Please keep us posted on progress!

**Comment by GeorgeGayno-NOAA** [comment]
Can you provide some specifics on the updates?

**Comment by jwolff-ncar** [comment]
@LarissaReames-NOAA Please add details as you begin to work on this merger. Thank you!

**Comment by LarissaReames-NOAA** [comment]
@GeorgeGayno-NOAA If you'll remember there was quite a bit of code removed related to grib2 data coming from other model sources, particularly those on grids other than lat-lon and those on native hybrid vertical coordinates. I'll be adding that code back in, as well as some code that GSL had previously requested (and that's currently in use in realtime regional runs at GSL) that allows for the use of input vegetation and soil data on the output grid instead of climatology. I'll of course keep this branch separate from the MRW release branch since that only had the code to read in GFS grib2 data, but it will be built on-top of that branch to preserve all of that functionality.

**Comment by GeorgeGayno-NOAA** [comment]
This was completed under #146.  Closing this issue.
